### ISSUE TITLE
Start Failed: Failed to initialize graphics environment

### ISSUE THREAD

**Issue by pravinsakthivel** [DrSnowbird/intellij-docker#1]
I have my x11 server in windows 10 running, and specified DISPLAY option as
export DISPLAY = localhost:0.0
export DISPLAY = :0
export DISPLAY = <IP>:0.0

still nothing works, fails with below error
Start Failed: Failed to initialize graphics environment

java.awt.AWTError: Can't connect to X11 window server using 'localhost:0.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.Toolkit$2.run(Toolkit.java:860)
        at java.awt.Toolkit$2.run(Toolkit.java:855)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
        at com.intellij.ui.AppUIUtil.updateFrameClass(AppUIUtil.java:161)
        at com.intellij.idea.StartupUtil.prepareAndStart(StartupUtil.java:94)
        at com.intellij.idea.MainImpl.start(MainImpl.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.ide.plugins.PluginManager.lambda$start$0(PluginManager.java:75)
        at java.lang.Thread.run(Thread.java:748)

**Comment by laur89** [comment]
Does your x server allow connections? try running `xhost +` from the host running the server.

**Comment by DrSnowbird** [comment]
I don't have Windows Host setup. Mostly, you have to use something Xmin with X11 to launch. Try resources like below to setup your Windows for X11 (use example xclock or xeye as simple test. If it works, then the X11 docker images should work too).
https://cc.jlab.org/windows/X11onWindow
